### PR TITLE
Resolves #3781 - Long avatar URL causes MySQL error

### LINKED ISSUE #3781: Long avatar URL causes MySQL error
There should probably be better validation for this.

SQL Error:
1406 - Data too long for column 'avatar' at row 1
Query:
UPDATE mybb_users SET `avatar`='http:...', `avatardimensions`='62|62', `avatartype`='remote' WHERE uid='1'

### PR DESCRIPTION
**Pull request by Ben-MyBB**
Resolves #3781

### CODE REVIEW

File: usercp.php [hunk 1]
```diff
@@ -2485,6 +2485,12 @@
 				}
 			}
 
+			// Limiting URL string to stay within database limit
+			if(strlen($mybb->input['avatarurl']) > 200)
+			{
+					$avatar_error = $lang->error_avatarurltoolong;
```
Comment (Eldenroot) [inline usercp.php:2491]: formatting :)

File: inc/languages/english/usercp.lang.php [hunk 2]
```diff
@@ -299,6 +299,7 @@
 $l['attachstats_quota'] = "Attachment Quota";
 $l['attachstats_totaldl'] = "Total Downloads";
 $l['attachstats_bandwidth'] = "Approximate Bandwidth Usage";
+$l['error_avatarurltoolong'] = "Sorry, but we cannot change your avatar as the new avatar URL specified is too long. You can try to use a shorter URL which doesn't exceed the database field length.";
```
Comment (euantorano) [inline inc/languages/english/usercp.lang.php:302]: I think this is better worded without mentioning a DB field as that could confuse some users:

```suggestion
$l['error_avatarurltoolong'] = "Sorry, but we cannot change your avatar as the new avatar URL specified is too long. You can try to use a shorter URL which is less than 200 characters long.";
```

**Comment by Ben-MyBB** [comment]
Thanks @euantorano and @Eldenroot . Both updated plus a missing full-stop in another language string I spotted.
