### PR TITLE
Fix custom profile fields display in ACP (fixes #2905)

### LINKED ISSUE #2905: php 7.1.x errors - admin/modules/users.php
After updating to v1.8.13 (from v1.8.12; php 7.1.x) I get these php errors in ACP -> User & Groups -> Edit user -> Profile - these errors are shown below the setting. I use custom profile fields.

After discussion with @euantorano over Discord, he found that there is an issue on lane #4046 (admin/modules/users.php) - it creates an array, then overwrites it with an empty array.

I am enclosing image:
phperror

### PR DESCRIPTION
**Pull request by fluxtion**

### CODE REVIEW

**Comment by Eldenroot** [comment]
Thank you, you are on fire! Keep good work!

**Comment by fluxtion** [comment]
@Eldenroot Thanks! Fixing the simple stuff is helping me understand the codebase a lot better. :)

File: admin/modules/user/users.php [hunk 1]
```diff
@@ -3959,6 +3959,7 @@ function output_custom_profile_fields($fields, $values, &$form_container, &$form
 		switch($type)
 		{
 			case "multiselect":
+				$selected_options = array();
```
Comment (Shade-) [inline admin/modules/user/users.php]: Just a styling tip, can you add a newline before this? Thank you, keep it up!

File: admin/modules/user/users.php [hunk 2]
```diff
@@ -4033,6 +4034,7 @@ function output_custom_profile_fields($fields, $values, &$form_container, &$form
 				}
 				break;
 			case "checkbox":
+				$select_options = array();
```
Comment (Shade-) [inline admin/modules/user/users.php]: Same here

**Comment by fluxtion** [comment]
@Shade- Sure. I just used the existing format though. I didn't want to tread on anyone's toes.

**Comment by fluxtion** [comment]
@Shade- This is ready to be merged I think. Please check I satisfied your coding conventions. :-)

**Comment by Shade-** [comment]
Sorry, my bad, thought we were adding a newline after switch/case statements from a quick look, but on a more focused one I realized we don't. Could you please delete the newlines? Thank you!

File: admin/modules/user/users.php [hunk 3]
```diff
@@ -4033,6 +4037,8 @@ function output_custom_profile_fields($fields, $values, &$form_container, &$form
 				}
 				break;
 			case "checkbox":
+				
+				$select_options = array();
```
Comment (Shade-) [inline admin/modules/user/users.php]: Not sure why this has been moved here though. It was fine where it was before

File: admin/modules/user/users.php [hunk 4]
```diff
@@ -3959,6 +3959,8 @@ function output_custom_profile_fields($fields, $values, &$form_container, &$form
 		switch($type)
 		{
 			case "multiselect":
+				
+				$selected_options = array();
```
Comment (Shade-) [inline admin/modules/user/users.php]: Same for this.

File: admin/modules/user/users.php (hunk 3 above)
Comment (fluxtion) [reply admin/modules/user/users.php]: For consistency. Isn't it easier for you to just reformat this however you want? 4 formatting commits for a 4 line fix is just odd. You can edit my changes right?

Comment (Shade-) [reply admin/modules/user/users.php]: Ah alright, no actions required then :) Unfortunately I can't edit your changes as they are in your fork, and I don't have access to it. Don't worry about having many commits, as we stash them when merging, so they will be all compressed into a single one.

Comment (Shade-) [reply admin/modules/user/users.php]: Bump :)

Comment (JordanMussi) [reply admin/modules/user/users.php]: @Shade- You should be able to add commits to this branch if @fluxtion has [allowed edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests).

File: admin/modules/user/users.php (hunk 1 above)
Comment (JordanMussi) [reply admin/modules/user/users.php]: Since when was a newline after the case statement part of the standards? The example given in the [development standards](https://docs.mybb.com/1.8/development/standards/) doesn't have an extra newline.

Comment (Shade-) [reply admin/modules/user/users.php]: Yep my bad, already asked @fluxtion to remove it below.

Comment (JordanMussi) [reply admin/modules/user/users.php]: Ah yes, seen now! 🙂

File: admin/modules/user/users.php (hunk 3 above)
Comment (fluxtion) [reply admin/modules/user/users.php]: @JordanMussi I have indeed but since @Shade- isn't around, I'm just going to make the changes so we can finally merge this. I don't like having so many open PRs that are completely ready for merging.

**Comment by fluxtion** [comment]
Okay, coding conventions are satisfied, @Shade- is happy. Everything is good. Can we please merge this now? @kawaii @euantorano 

This took far longer than I would've liked for a simple 6 line fix. :(
