### PR TITLE
Fix #307 User Pruning bug

### LINKED ISSUE #307: User Pruning bug
> When user pruning people with less than x posts, the user may in fact have the required amount of posts but they may not show up in the mybb_users postnum field due to the posts not counting in a certain forum, e.g. the "Testing" forum on MyBB.
> 
> An example would be pruning a user who has posted in the /me thread 50 times but no where else, maintaining a post count of 0. If the pruner would be run, they would be deleted.
> 
> I'm guessing this isn't intended, and probably should be looked into.

Original report: http://dev.mybb.com/issues/2139
Reporter: Paul H.
Status: Confirmed

### PR DESCRIPTION
**Pull request by Sama34**
Fix #307 User Pruning bug

### CODE REVIEW

File: inc/tasks/userpruning.php [hunk 1]
```diff
@@ -41,11 +41,25 @@ function task_userpruning($task)
 			unset($in_usergroups[$key]);
 		}
 
-		$regdate = TIME_NOW-((int)$mybb->settings['dayspruneregistered']*24*60*60);
-		$query = $db->simple_select("users", "uid", "regdate <= ".(int)$regdate." AND postnum <= ".(int)$mybb->settings['prunepostcount']." AND usergroup IN(".$db->escape_string(implode(',', $in_usergroups)).")");
-		while($user = $db->fetch_array($query))
+		$prunepostcount = (int)$mybb->settings['prunepostcount'];
+
+		$regdate = (int)(TIME_NOW-((int)$mybb->settings['dayspruneregistered']*24*60*60));
+		$query = $db->simple_select('users', 'uid', "regdate<={$regdate} AND postnum<={$prunepostcount} AND usergroup IN({$db->escape_string(implode(',', $in_usergroups))})");
```
Comment (Stefan-ST) [inline inc/tasks/userpruning.php]: You can't call a function like that.

File: inc/tasks/userpruning.php [hunk 2]
```diff
@@ -41,11 +41,25 @@ function task_userpruning($task)
 			unset($in_usergroups[$key]);
 		}
 
-		$regdate = TIME_NOW-((int)$mybb->settings['dayspruneregistered']*24*60*60);
-		$query = $db->simple_select("users", "uid", "regdate <= ".(int)$regdate." AND postnum <= ".(int)$mybb->settings['prunepostcount']." AND usergroup IN(".$db->escape_string(implode(',', $in_usergroups)).")");
-		while($user = $db->fetch_array($query))
+		$prunepostcount = (int)$mybb->settings['prunepostcount'];
+
+		$regdate = (int)(TIME_NOW-((int)$mybb->settings['dayspruneregistered']*24*60*60));
```
Comment (Stefan-ST) [inline inc/tasks/userpruning.php]: Why do you intval the result of a calculation? It will always be numeric.

File: inc/tasks/userpruning.php (hunk 1 above)
Comment (Sama34) [inline inc/tasks/userpruning.php]: Well, I just did and it worked. Or are you saying I'm not allowed to?

Comment (Stefan-ST) [inline inc/tasks/userpruning.php]: Okay, it works (actually I never tried) but you should probably stick with common way which is IMHO more readable.

File: inc/tasks/userpruning.php [hunk 3]
```diff
@@ -41,11 +41,25 @@ function task_userpruning($task)
 			unset($in_usergroups[$key]);
 		}
 
+		$prunepostcount = (int)$mybb->settings['prunepostcount'];
+
 		$regdate = TIME_NOW-((int)$mybb->settings['dayspruneregistered']*24*60*60);
-		$query = $db->simple_select("users", "uid", "regdate <= ".(int)$regdate." AND postnum <= ".(int)$mybb->settings['prunepostcount']." AND usergroup IN(".$db->escape_string(implode(',', $in_usergroups)).")");
-		while($user = $db->fetch_array($query))
+		$query = $db->simple_select('users', 'uid', "regdate<={$regdate} AND postnum<={$prunepostcount} AND usergroup IN({$db->escape_string(implode(',', $in_usergroups))})");
+		while($uid = (int)$db->fetch_field($query, 'uid'))
```
Comment (Destroy666x) [inline inc/tasks/userpruning.php]: Casting not needed, uid field in the databse has to be integer.

Comment (Sama34) [inline inc/tasks/userpruning.php]: Well, the results are used in the following query so I'm not going to remove this one.

Comment (Destroy666x) [inline inc/tasks/userpruning.php]: Not an issue (except increasing the file size and execution time a very tiny bit) but still doesn't make much sense to use it here. It's not an user input so the extra security layer is never needed in this case, unless someone hacks the database, changes the `uid` column to another type, injects malicious strings and then runs this query, which would be the weirdest attack ever.

File: inc/tasks/userpruning.php [hunk 4]
```diff
@@ -41,11 +41,28 @@ function task_userpruning($task)
...
+		$prunepostcount = (int)$mybb->settings['prunepostcount'];
+
 		$regdate = TIME_NOW-((int)$mybb->settings['dayspruneregistered']*24*60*60);
-		$query = $db->simple_select("users", "uid", "regdate <= ".(int)$regdate." AND postnum <= ".(int)$mybb->settings['prunepostcount']." AND usergroup IN(".$db->escape_string(implode(',', $in_usergroups)).")");
-		while($user = $db->fetch_array($query))
+
+		$usergroups = $db->escape_string(implode(',', $in_usergroups));
+
+		$query = $db->simple_select('users', 'uid', "regdate<={$regdate} AND postnum<={$prunepostcount} AND usergroup IN({$usergroups})");
+		while($uid = (int)$db->fetch_field($query, 'uid'))
```
Comment (Destroy666x) [inline inc/tasks/userpruning.php]: > Well, the results are used in the following query so I'm not going to remove this one.
It is no real issue at all.

Not an issue (except increasing the file size and execution time a very tiny bit), but still doesn't make much sense to use it here. It's not an user input so the extra security layer is never needed in this case, unless someone hacks the database, changes the uid column to another type, injects malicious string to a record and then runs this query, which would be the weirdest attack ever.

File: inc/tasks/userpruning.php (hunk 3 above)
Comment (Sama34) [inline inc/tasks/userpruning.php]: I'm going to avoid replying every one of your points and just remove it.

**Comment by Sama34** [comment]
Now if somebody can confirm this does works and/or merge I would really appreciate. I would like to fix #1711 which is the last PR of mine and then fix my repository to jump to new issues.

Yeah I know this is tagged for 1.8.5 but I missed that when sending the PR.

**Comment by Destroy666x** [comment]
What about the soft-deleted/unapproved posts and drafts?

**Comment by Cu8eR** [comment]
This needs to be merged before #1151 right?

**Comment by Sama34** [comment]
I have updated this to ignore any deleted/unapproved post but it certainly won't consider the status of the thread it self, so the user can still appear to have  zero posts.

I don't think adding thread status verification to be so necessary, but if you disagree please comment otherwise I would appreciate this being merged because as @Cu8eR mentioned I need this to fix my last PR.

**Comment by Sama34** [comment]
I will get this merged if no one rejects.

**Comment by Destroy666x** [comment]
A peeker should be added: https://github.com/mybb/mybb/blob/feature/admin/modules/config/settings.php#L1617

Except that it looks ok, but I haven't tested it.

**Comment by Sama34** [comment]
That is the first conflict. The file differs from my own.

**Comment by Sama34** [comment]
I have pushed directly.

e6853da2da3f70a12a4e7ea4235a31d64737b887
