### PR TITLE
Fix #1845 PM Verification Incorrect (ignore list)

### LINKED ISSUE #1845: PM Verification Incorrect (ignore list)
Hi,

inc/datahandlers/pm.php

PHP Code:
  &nbsp;   &nbsp;   &nbsp;    &nbsp;&#36;ignorelist&nbsp;=&nbsp;explode(",",&nbsp;&#36;user['ignorelist']);  &nbsp;   &nbsp;   &nbsp;   &nbsp; if(!empty(&#36;ignorelist)&nbsp;&amp;&amp;&nbsp;in_array(&#36;pm['fromid'],&nbsp;&#36;ignorelist))  &nbsp;   &nbsp;   &nbsp;   &nbsp; {  &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp; &#36;this-&gt;set_error("recipient_is_ignoring",&nbsp;array(&#36;user['username']));  &nbsp;   &nbsp;   &nbsp;   &nbsp; }&nbsp;

That is wrong. &#36;user['ignorelist'] should be checked if it's empty before exploding it, otherwise an array will be created:

Code:
array (
     [0] =&gt;
)

At first glance there are no problems. Now look at send_pm in functions.php. &#36;fromid can be set to 0 / empty, therefore in_array(&#36;pm['fromid'], &#36;ignorelist) is true even though the ignorelist is empty.

Fix:

PHP Code:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(&#36;user['ignorelist']&nbsp;!=&nbsp;'')&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;ignorelist&nbsp;=&nbsp;explode(",",&nbsp;&#36;user['ignorelist']);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(!empty(&#36;ignorelist)&nbsp;&amp;&amp;&nbsp;in_array(&#36;pm['fromid'],&nbsp;&#36;ignorelist))&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;this-&gt;set_error("recipient_is_ignoring",&nbsp;array(&#36;user['username']));&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;

The same thing should be done to the buddy list (a few lines below).

Regards,
Diogo

Original thread: [PM Verification Incorrect (ignore list)](http://community.mybb.com/thread-167291.html)

### PR DESCRIPTION
**Pull request by Sama34**
Fix #1845 PM Verification Incorrect (ignore list)

### CODE REVIEW

File: inc/datahandlers/pm.php [hunk 1]
```diff
@@ -293,19 +293,22 @@ function verify_recipient()
 			// - sender is an administrator
 			if(($this->admin_override != true && $sender_permissions['cancp'] != 1) && $sender_permissions['canoverridepm'] != 1)
 			{
-				$ignorelist = explode(",", $user['ignorelist']);
-				if(!empty($ignorelist) && in_array($pm['fromid'], $ignorelist))
+				if(!empty($user['ignorelist']))
 				{
-					$this->set_error("recipient_is_ignoring", array($user['username']));
+					$ignorelist = explode(',', $user['ignorelist']);
+					if(!empty($ignorelist) && in_array($pm['fromid'], $ignorelist))
```
Comment (Destroy666x) [inline inc/datahandlers/pm.php]: `!empty()` not needed here and in line 309, they don't do anything because `$user['ignorelist']` and `$user['buddylist']` are checked earlier and they're surely filled there.

**Comment by Sama34** [comment]
I used `my_strpos()` instead.

File: inc/datahandlers/pm.php [hunk 2]
```diff
@@ -293,20 +293,15 @@ function verify_recipient()
 			// - sender is an administrator
 			if(($this->admin_override != true && $sender_permissions['cancp'] != 1) && $sender_permissions['canoverridepm'] != 1)
 			{
-				$ignorelist = explode(",", $user['ignorelist']);
-				if(!empty($ignorelist) && in_array($pm['fromid'], $ignorelist))
+				if(!empty($user['ignorelist']) && my_strpos(','.$user['ignorelist'].',', ','.$pm['fromid'].',') !== false)
```
Comment (Destroy666x) [inline inc/datahandlers/pm.php]: `strpos()` is sufficient here, there are no Unicode characters in `$user['ignorelist']`/`$user['buddylist']`

Comment (Sama34) [inline inc/datahandlers/pm.php]: Done.
