### PR TITLE
Fixes #2763 Random password at registration doesn't work

### LINKED ISSUE #2763: Random password at registration doesn't work
The password randomly generated at registration doesn't work because its hash is inserted into the mail instead of the actually password.

### PR DESCRIPTION
**Pull request by JordanMussi**
Fixes #2763

### CODE REVIEW

File: member.php [hunk 1]
```diff
@@ -443,16 +443,16 @@
 			switch($mybb->settings['username_method'])
 			{
 				case 0:
-					$emailmessage = $lang->sprintf($lang->email_randompassword, $user['username'], $mybb->settings['bbname'], $user_info['username'], $user_info['password']);
+					$emailmessage = $lang->sprintf($lang->email_randompassword, $user['username'], $mybb->settings['bbname'], $user_info['username'], $mybb->input['password']);
```
Comment (euantorano) [inline member.php]: Should probably use `$mybb->get_input()` here just for the sake of following what's used elsewhere.

Comment (JordanMussi) [inline member.php]: Sure - done in 6a8025a6938ac1ef656b7cc0228574b31dec8ea6
