### PR TITLE
Fixes #2122 Quick reply wrong $postcounter

### LINKED ISSUE #2122: Quick reply wrong $postcounter
After making a quick in a post where there are soft deleted posts the reply apepasr in the same page, after refreshing the post is moved to another page if applicable.

PHP Code:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Set&nbsp;post&nbsp;counter&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(&#36;ismod&nbsp;==&nbsp;true)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;postcounter&nbsp;=&nbsp;&#36;thread['replies']&nbsp;+&nbsp;&#36;thread['unapprovedposts']&nbsp;+&nbsp;1;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;postcounter&nbsp;=&nbsp;&#36;thread['replies']&nbsp;+&nbsp;1;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;

The ajax quick reply code doesn't considers soft deleted posts and assumes the moderator can see unapproved/deleted posts.

Original thread: [Quick reply wrong $postcounter](http://community.mybb.com/thread-168745.html)

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2122

### CODE REVIEW

File: newreply.php [hunk 1]
```diff
@@ -604,13 +604,17 @@
 			if($visible == 1)
 			{
 				// Set post counter
+				$postcounter = $thread['replies'] + 1;
 				if($ismod == true)
```
Comment (Destroy666x) [inline newreply.php]: This check is not needed anymore.

Comment (PaulBender) [inline newreply.php]: I've changed it.
