### PR TITLE
Update 1.9 theme style and associated fixes

### LINKED ISSUE #5201: Add table header to User CP's Security Log

### PR DESCRIPTION
**Pull request by justinsoltesz**
Includes a number of changes to the theme to update, standardize, and otherwise clean up the design. Also includes a number of fixes associated with these changes.

I am still working through some additional clean up and testing, so making this a draft pull request for now.

Resolves #5201

### CODE REVIEW

File: inc/src/Twig/Extensions/CoreExtension.php [hunk 1]
```diff
@@ -376,17 +376,23 @@ public function numberFormat($number): string
...
      *
      * @throws \Twig\Error\LoaderError
      * @throws \Twig\Error\RuntimeError
      * @throws \Twig\Error\SyntaxError
      */
-    public function buildBreadcrumbNavigation(Environment $twig): string
-    {
+    public function buildBreadcrumbNavigation(
+        Environment $twig,
+        ?string $class = ''
```
Comment (Sama34) [inline inc/src/Twig/Extensions/CoreExtension.php:389]: Is a null value expected in core ?

Comment (justinsoltesz) [reply inc/src/Twig/Extensions/CoreExtension.php:389]: This only adds the modifier class (`.breadcrumb--header` or `.breadcrumb--footer` in core); the base `.breadcrumb` class is already applied in the template. So while the core theme applies a modifier class at both places the breadcrumb is used, it isn't required to show and style the breadcrumb. All `.breadcrumb--header` does is hide the active link, and `.breadcrumb--footer` currently doesn't do anything.

**Review by arcalys — APPROVED** [review]

**Review by arcalys — APPROVED** [review]
