### PR TITLE
Fixes #3170 MySQL error with strict mode if message too long - Extended

### LINKED ISSUE #3170: MySQL error with strict mode if message too long
If the message is longer than the limit of the message field in the database, with MySQL strict mode enabled it throws an error instead of cutting the message after the limit.

Code:SQL Error:
1406 - Data too long for column 'message' at row 1
To avoid this error in our forum, I added in function verify_message() in inc/datahandlers/post.php below

PHP Code://&nbsp;If&nbsp;this&nbsp;board&nbsp;has&nbsp;a&nbsp;maximum&nbsp;message&nbsp;length&nbsp;check&nbsp;if&nbsp;we're&nbsp;over&nbsp;it.&nbsp;Use&nbsp;strlen&nbsp;because&nbsp;SQL&nbsp;limits&nbsp;are&nbsp;in&nbsp;byteselse&nbsp;if(strlen(&#36;post['message'])&nbsp;&gt;&nbsp;&#36;mybb-&gt;settings['maxmessagelength']&nbsp;&amp;&amp;&nbsp;&#36;mybb-&gt;settings['maxmessagelength']&nbsp;&gt;&nbsp;0&nbsp;&amp;&amp;&nbsp;!is_moderator(&#36;post['fid'],&nbsp;"",&nbsp;&#36;post['uid'])){ &nbsp; &nbsp;&#36;this-&gt;set_error("message_too_long",&nbsp;array(&#36;mybb-&gt;settings['maxmessagelength'],&nbsp;strlen(&#36;post['message']))); &nbsp; &nbsp;return&nbsp;false;}&nbsp;
a check:

PHP Code://&nbsp;If&nbsp;the&nbsp;message&nbsp;length&nbsp;is&nbsp;over&nbsp;SQL&nbsp;limitselse&nbsp;if(strlen(&#36;post['message'])&nbsp;&gt;&nbsp;65535){ &nbsp; &nbsp;global&nbsp;&#36;db; &nbsp; &nbsp;&#36;fieldlength&nbsp;=&nbsp;&#36;db-&gt;show_fields_from("posts"); &nbsp; &nbsp;if(is_array(&#36;fieldlength)) &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp;foreach&nbsp;(&#36;fieldlength&nbsp;as&nbsp;&#36;key&nbsp;=&gt;&nbsp;&#36;fields) &nbsp; &nbsp; &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if(&#36;fields['Field']&nbsp;==&nbsp;'message') &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;switch(&#36;fields['Type']) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;case&nbsp;'text': &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&#36;maximum&nbsp;=&nbsp;65535; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;break; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;case&nbsp;'mediumtext': &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&#36;maximum&nbsp;=&nbsp;16777215; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;break; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;case&nbsp;'longtext': &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&#36;maximum&nbsp;=&nbsp;4294967295; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;break; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;default: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&#36;maximum&nbsp;=&nbsp;65535; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;} &nbsp; &nbsp; &nbsp; &nbsp;} &nbsp; &nbsp;} &nbsp; &nbsp;if(isset(&#36;maximum)&nbsp;&amp;&amp;&nbsp;strlen(&#36;post['message'])&nbsp;&gt;&nbsp;&#36;maximum) &nbsp; &nbsp;{ &nbsp; &nbsp; &nbsp; &nbsp;&#36;this-&gt;set_error("message_too_long",&nbsp;array(&#36;maximum,&nbsp;strlen(&#36;post['message']))); &nbsp; &nbsp; &nbsp; &nbsp;return&nbsp;false; &nbsp; &nbsp;}}&nbsp;

Original thread: [MySQL error with strict mode if message too long](https://community.mybb.com/thread-210436.html)

### PR DESCRIPTION
**Pull request by effone**
Covered field types for MySQL
Revised settings description.

### CODE REVIEW

File: inc/datahandlers/post.php [hunk 1]
```diff
@@ -252,28 +252,60 @@ function verify_message()
...
+				if($limit > 0 && $dblimit > 0)
+				{
+					$limit = min($limit, $dblimit);
+				}
+				else
+				{
+					$limit = max($limit, $dblimit);
+				}
+
+				if(strlen($post['message']) > $limit && (!is_moderator($post['fid'], "", $post['uid']) || $limit == $dblimit))
```
Comment (chack1172) [inline inc/datahandlers/post.php]: This condition is not working well. If an administrator/moderator sends a message longer than $dblimit, this condition lets him post it because $limit is the post limit and not the db limit. You should remove the is_moderator condition here and move it where is $limit declared.

File: inc/datahandlers/post.php [hunk 2]
```diff
@@ -252,28 +252,60 @@ function verify_message()
...
 		}
-
-		// If this board has a maximum message length check if we're over it. Use strlen because SQL limits are in bytes
-		else if(strlen($post['message']) > $mybb->settings['maxmessagelength'] && $mybb->settings['maxmessagelength'] > 0 && !is_moderator($post['fid'], "", $post['uid']))
+		else
 		{
-			$this->set_error("message_too_long", array($mybb->settings['maxmessagelength'], strlen($post['message'])));
-			return false;
-		}
+			$limit = (int)$mybb->settings['maxmessagelength'];
```
Comment (chack1172) [inline inc/datahandlers/post.php]: Here you should add the is_moderator condition:
```php
			if(!is_moderator($post['fid'], '', $post['uid']))
			{
				$limit = (int)$mybb->settings['maxmessagelength'];
			}
			else
			{
				$limit = 0;
			}
```

File: inc/datahandlers/post.php (hunk 1 above)
Comment (chack1172) [reply inc/datahandlers/post.php]: I suggest you to change it with this:
```php
				if($limit > $dblimit)
				{
					$limit = $dblimit;
				}
				if(strlen($post['message']) > $limit)
				{
```

File: inc/datahandlers/post.php (hunk 2 above)
Comment (effone) [reply inc/datahandlers/post.php]: Logic updated. Thanks for review.
