### PR TITLE
Fix for #4219

### LINKED ISSUE #4219: Password Length Settings
In ACP > Login and Registration Options, Minimum Password Length (`minpasswordlength`) can be set greater than Maximum Password Length (`maxpasswordlength`).
There is no validation in place. Resulting user impossible to register.

### PR DESCRIPTION
**Pull request by Xazin**
Resolves #4219

- minnamelength cannot be larger than maxnamelength
- minpasswordlength cannot be larger than maxpasswordlength
- If complex password is required minpasswordlength cannot be less than 3 (1 uppercase, 1 lowercase & 1 number = 3 chars)

### CODE REVIEW

File: admin/modules/config/settings.php [hunk 1]
```diff
@@ -965,6 +965,28 @@
 			}
 		}
 
+		// Validate minnamelength, maxnamelength, minpasswordlength (complex and regular) and maxpasswordlength
+		if ($gid == 9)
```
Comment (Sama34) [inline admin/modules/config/settings.php:969]: We should avoid magic numbers on the future. @mybb/developers
