### PR TITLE
Fixes #1989 IP Search shows moderators thread titles even if they hav…

### LINKED ISSUE #1989: IP Search shows moderators thread titles even if they have no permission there.
Detailed description of your problem, including steps to reproduce if necessary

Person has mod CP access. It can get the IP address of a user that has view access to a board the moderator doesn't. They go to Mod CP, IP Search and put in the IP address of the user. They will be able to see the TITLES of THREADS the user has created or posted in, even if the mod with Mod CP access doesn't have view permission on these boards.
New installation or upgrade (from which version of MyBB)?

1.6

Thanks

P.S: I've temporarily commented out the "Search Posts" checkbox under IP Search, but that's not a very safe solution.

Original thread: [IP Search shows moderators thread titles even if they have no permission there.](http://community.mybb.com/thread-170811.html)

### PR DESCRIPTION
**Pull request by PaulBender**
…e no permission there.

Fixes #1989

Checks against forum permission (to see if user can view that thread/post) and moderator permission (to see if user can view that post if unapproved/deleted).

### CODE REVIEW

File: modcp.php [hunk 1]
```diff
@@ -3569,7 +3569,69 @@
...
-				$query = $db->simple_select('posts', 'COUNT(pid) AS count', "$post_ip_sql AND visible >= -1");
+				$where_sql = '';
+				$unviewablefids = array();
+				$onlyusfids = array();
+
+				// Check group permissions if we can't view posts not started by us
+				$group_permissions = forum_permissions();
+				foreach($group_permissions as $fid => $forumpermissions)
+				{
+					if($forumpermissions['canview'] == 0 || $forumpermissions['canviewthreads'] == 0)
```
Comment (Destroy666x) [inline modcp.php]: Filtering by `get_unviewable_forums()` results would be better than this conditional since passwords are also checked there. `get_inactive_forums()` should also be used.

**Comment by Destroy666x** [comment]
The `canonlyviewownthreads` conditional should have stayed though, `get_unviewable_forums(true)` doesn't check that. However, the `$onlyusfids` part of the query was wrong - it checked the `uid` column in the `posts` table, which is the author of the post and not the thread. `LEFT JOIN` to the `threads` table will probably be needed in both queries.

**Comment by PaulBender** [comment]
That should do it.

File: modcp.php [hunk 2]
```diff
@@ -3569,7 +3569,77 @@
...
+
+						if($moderator['canviewdeleted'] == 1)
+						{
+							$deleted_forums[] = $moderator['fid'];
+						}
+					}
+
+					if(!empty($unapprove_forums))
+					{
+						$visible_sql .= " OR (p.visible = 0 AND p.fid IN(".implode(',', $unapprove_forums)."))";
```
Comment (Destroy666x) [inline modcp.php]: Doesn't `$visible_sql = ' AND p.visible > 0 AND t.visible > 0';` + this skip unapproved (and soft deleted below) posts?

If I'm not mistaken, `p.visible > 0` is always required by `AND` and the OR applies to `t.visible > 0` and the other 2 conditions.

**Comment by PaulBender** [comment]
Okay, I think I've fixed the thread visibility (at least it works for me).

**Comment by euantorano** [comment]
Works for me too, merging.
