### PR TITLE
Fix - Inefficient thread moderation code - threads queried one by one

### LINKED ISSUE #2114: Inefficient thread moderation code - threads queried one by one
As the title says:
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L3650
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L538
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L3496
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L388

All `tids`/`pids` are known so I'm not sure why a single query with a left join to the `forums` table + a while loop for results weren't used in the first place.

### PR DESCRIPTION
**Pull request by rajat315315**
Closes #2114

### CODE REVIEW

File: inc/class_moderation.php [hunk 1]
```diff
@@ -534,9 +543,18 @@ function unapprove_threads($tids)
...
+			$threads[$thread['tid']] = $thread;
+		}
+
 		foreach($tids as $tid)
 		{
-			$thread = get_thread($tid);
+			$thread = $threads[$tid];
 			$forum = get_forum($thread['fid']);
 
 			if($thread['visible'] == 1 || $thread['visible'] == -1)
```
Comment (Sama34) [inline inc/class_moderation.php]:
```suggestion
			if(!$thread || $thread['visible'] == 1 || $thread['visible'] == -1)
```

File: inc/class_moderation.php [hunk 2]
```diff
@@ -3649,9 +3675,17 @@ function soft_delete_threads($tids)
...
+			$threads[$thread['tid']] = $thread;
+		}
+
 		foreach($tids as $tid)
 		{
-			$thread = get_thread($tid);
+			$thread = $threads[$tid];
 			$forum = get_forum($thread['fid']);
 
 			if($thread['visible'] == 1 || $thread['visible'] == 0)
```
Comment (Sama34) [inline inc/class_moderation.php]:
```suggestion
			if(!$thread || $thread['visible'] == 1 || $thread['visible'] == 0)
```

**Review by Sama34 — CHANGES_REQUESTED** [review]
