### PR TITLE
Fix `undefined` issues

### LINKED ISSUE #4485: Fix PHP 8.0 compatibility problems (continued)
Following #4138, we'll continue fixing any PHP 8.0 compatibility issue.

### PR DESCRIPTION
**Pull request by dvz**
Resolves #4485

### CODE REVIEW

File: admin/modules/config/plugins.php [hunk 1]
```diff
@@ -219,7 +219,7 @@
 			}
 			$plugininfo = $infofunc();
 			$plugininfo['guid'] = isset($plugininfo['guid']) ? trim($plugininfo['guid']) : null;
-			$plugininfo['codename'] = trim($plugininfo['codename']);
+			$plugininfo['codename'] = isset($plugininfo['guid']) ? trim($plugininfo['codename']) : null;
```
Comment (yuliu) [inline admin/modules/config/plugins.php]: Looks like a copy-paste typo here 🤣
