### PR TITLE
Fix "undefined" and type issues

### LINKED ISSUE #4138: Fix PHP 8.0 compatibility problems
- [x] Various compatibility issues: #4095
- [x] Common _undefined_ errors — Admin CP: #4207
- [x] Common _undefined_ errors — front-end

### PR DESCRIPTION
**Pull request by dvz**
Fix issues related to PHP Errors and Warnings on PHP 8.

Partially resolves .#4138

### CODE REVIEW

File: inc/functions.php [hunk 1]
```diff
@@ -1014,7 +1017,7 @@ function redirect($url, $message="", $title="", $force_redirect=false)
 	}
 
 	// Show redirects only if both ACP and UCP settings are enabled, or ACP is enabled, and user is a guest, or they are forced.
-	if($force_redirect == true || ($mybb->settings['redirects'] == 1 && ($mybb->user['showredirect'] == 1 || !$mybb->user['uid'])))
+	if($force_redirect == true || ($mybb->settings['redirects'] == 1 && (!$mybb->user['uid'] || !$mybb->user['showredirect'] == 1)))
```
Comment (Stefan-MyBB) [inline inc/functions.php:1020]: @dvz `$mybb->user['showredirect'] == 1` was accidentally changed to `!$mybb->user['showredirect'] == 1`. Note the exclamation mark.
