### PR TITLE
Mass mail fixes

### LINKED ISSUE #4183: Mass mail: lost radio button selection & illegal string offset warnings
Mass mail at AdminCP:

1. If the scheduled sending date is in past, the error message screen loses that radio button selection.

Creating:

[attachment=43244]

Editing:

[attachment=43243]

2. When creating a new mass mailing, navigating away before submitting recipients criteria would result in blank in conditions in table massemails for this mass mailing. And warnings of Illegal string offset will be given when editing this mass mailing with PHP 7.4+.

One example of the warnings:
Warning [2] Illegal string offset 'username' - Line: 540 - File: \admin\modules\user\mass_mail.php PHP 7.4.1 (WINNT)
File 	Line 	Function
\admin\modules\user\mass_mail.php 	540 	errorHandler-&gt;error
\admin\index.php 	824 	require

Original thread: [Mass mail: lost radio button selection & illegal string offset warnings](https://community.mybb.com/thread-229293.html)

### PR DESCRIPTION
**Pull request by effone**
Resolves #4183

### CODE REVIEW

File: admin/modules/user/mass_mail.php [hunk 1]
```diff
@@ -59,6 +59,22 @@
 	{
 		$email['conditions'] = my_unserialize($email['conditions']);
 	}
+	else
+	{
+		// Fill the conditions with default values
+		$email['conditions'] = Array(
```
Comment (Sama34) [inline admin/modules/user/mass_mail.php]: Capitalized `Array` word might need to be changed.

File: admin/modules/user/mass_mail.php [hunk 2]
```diff
@@ -675,6 +691,7 @@ function insertText(value, textarea)
 		{
 			$page->output_inline_error($errors);
 			$input = $mybb->input;
+			$delivery_type_checked[$input['delivery_type']] = " checked=\"checked\"";
```
Comment (Sama34) [inline admin/modules/user/mass_mail.php:701]: I think we need to check if `$input['delivery_type']` is set. Maybe just `$mybb->get_input('delivery_type')`

**Review by Sama34 — CHANGES_REQUESTED** [review]
