### PR TITLE
Fix #1654, #1669 and #1670 - announcements no permission error, wrong $unvie...

### LINKED ISSUE #1654: Hidden forum stats.php appears
Forum permissions closed. But appear in the statistics.

"Forum" view closed.

Original thread: [Hidden forum stats.php appears](http://community.mybb.com/thread-163221.html)

### PR DESCRIPTION
**Pull request by Destroy666x**
...wablefids and incorrect caching in stats.php.

Merged arrays with unviewable fids so that all are considered now:
https://github.com/mybb/mybb/issues/1669

And corrected variable in 2 conditionals to fix this:
https://github.com/mybb/mybb/issues/1670

Removed forum caching from stats.php since the unviewable values may be different for each user so can't really store that.
https://github.com/mybb/mybb/issues/1654

Updated the list of cookies that should be cleared in misc.php.

Also optimised and made consistent some stuff - removed unused variables, selected only needed fields in query, changed some queries to `simple_select()`, etc.

### CODE REVIEW

File: modcp.php [hunk 1]
```diff
@@ -3665,7 +3631,7 @@
 		{
 			if(!empty($mybb->input[$input]))
 			{
-				$page_url .= "&amp;{$input}=".htmlspecialchars_uni($mybb->input[$input]);
+				$page_url .= "&amp;{$input}=".urlencode($mybb->input[$input]);
```
Comment (Destroy666x) [inline modcp.php]: These lines are for 2 different things - this one is for `array('ipaddress', 'search_users', 'search_posts')` and the one you linked for `array('username', 'sortby', 'order')`.

Comment (Sama34) [inline modcp.php]: You are right.

**Comment by Destroy666x** [comment]
This should be finished.

**Comment by PaulBender** [comment]
I've tested everything I can think of, and I can't find anything wrong. If no one else has any problems, this can be merged.

File: inc/datahandlers/user.php [hunk 2]
```diff
@@ -1617,12 +1616,12 @@ function delete_posts($delete_uids=false)
 		// Delete Reports made to users's posts/threads
 		if(!empty($pids))
 		{
-			$db->delete_query('reportedcontent', 'type=\'posts\' AND id IN('.implode(',', $pids).')');
+			$db->delete_query('reportedcontent', "type='posts' AND id IN({$this->delete_uids})");
```
Comment (JN-Jones) [inline inc/datahandlers/user.php]: This shouldn't be changed.

Comment (Destroy666x) [inline inc/datahandlers/user.php]: Oops, fixed.

**Comment by JN-Jones** [comment]
Note to myself before I forget: code is ok, #1791 and #1669 are fixed. #1670 and #1654 need to be tested.

Please make more PRs next time, it's difficult to understand which change does what.

File: stats.php [hunk 3]
```diff
@@ -56,27 +56,22 @@
...
+
 if($unviewableforums)
 {
-	$fidnot .= "fid NOT IN ($unviewableforums) AND ";
-	$unviewableforumsfids = explode(',', str_replace("'", '', $unviewableforums));
-	foreach($unviewableforumsfids as $fid)
-	{
-		$unviewableforumsarray[] = (int)$fid;
-	}
+	$fidnot .= "AND fid NOT IN $unviewableforums";
```
Comment (JN-Jones) [inline stats.php]: Aren't you missing the brackets here?

File: stats.php [hunk 4]
```diff
@@ -56,27 +56,22 @@
...
 }
 if($inactiveforums)
 {
-	$fidnot .= "fid NOT IN ($inactiveforums) AND ";
-	$unviewableforumsfids = explode(',', $inactiveforums);
-	foreach($unviewableforumsfids as $fid)
-	{
-		$unviewableforumsarray[] = (int)$fid;
-	}
+	$fidnot .= "AND fid NOT IN $inactiveforums";
```
Comment (JN-Jones) [inline stats.php]: A above

File: stats.php (hunk 3 above)
Comment (Destroy666x) [inline stats.php]: Where? If you mean around the `$unviewableforums`, it's just a regular PHP syntax we're using in a lot of places in MyBB.

Comment (JN-Jones) [inline stats.php]: PHP doesn't have a problem with this. However the SQL is wrong: `IN (x,y,z)` or `NOT IN (x,y,z)` is right but `IN x,y,z` or `NOT IN x,y,z` will throw an error.

Comment (Destroy666x) [inline stats.php]: Ah, I'm blind, you mean these brackets. Yes, should be added.

**Comment by JN-Jones** [comment]
I can't find anymore issues. Would be good if someone else can also check it.

**Comment by Destroy666x** [comment]
Missing parentheses added.

**Comment by PaulBender** [comment]
I still don't see anything wrong. If no one else has problems, I'll merge in a few hours.

**Comment by Destroy666x** [comment]
Added one last thing - quick fix for https://github.com/mybb/mybb/issues/1802 since I edited this part in the PR anyways.

File: admin/modules/tools/mailerrors.php [hunk 5]
```diff
@@ -206,14 +206,9 @@
...
-
-	$query = $db->query("
-		SELECT *
-		FROM ".TABLE_PREFIX."mailerrors
-		WHERE 1=1 {$additional_sql_criteria}
-		ORDER BY dateline DESC
-		LIMIT {$start}, {$per_page}
-	");
+	
+	$query = $db>simple_select('mailerrors', '*', "1=1 $additional_sql_criteria", array('order_by' => 'dateline', 'order_dir' => 'DESC', 'limit_start' => $start, 'limit' => $per_page));
```
Comment (Sama34) [inline admin/modules/tools/mailerrors.php]: You are missing a `-` here.

File: inc/class_datacache.php [hunk 6]
```diff
@@ -687,15 +684,14 @@ function update_statistics()
...
-		$query = $db->simple_select('users', 'COUNT(*) AS posters', 'postnum>0');
+		$query = $db->simple_select('users', 'COUNT(uid) AS posters', 'postnum>0');
 		$posters = $db->fetch_field($query, 'posters');
 
 		$statistics = array(
 			'time' => TIME_NOW,
-			'top_forum' => (array)$forum,
 			'top_referrer' => (array)$topreferrer,
 			'top_poster' => (array)$topposter,
-			'posters' => (int)$posters,
```
Comment (Sama34) [inline inc/class_datacache.php]: Really? I'm a little concerned about your code modifying code that I implemented just for the sake of it, honestly. Does this means I'm entitled to revert your changes on my next PRs?

File: inc/datahandlers/user.php [hunk 7]
```diff
@@ -1446,13 +1446,13 @@ function delete_user($delete_uids, $prunecontent=0)
...
 
-		$this->delete_uids = '\''.implode('\',\'', $this->delete_uids).'\'';
+		$this->delete_uids = implode(',', $this->delete_uids);
 		
 		$this->delete_content();
 
 		// Delete the user
-		$query = $db->delete_query('users', 'uid IN('.$this->delete_uids.')');
-		$this->deleted_users = (int)$db->affected_rows($query);
+		$query = $db->delete_query('users', "uid IN({$this->delete_uids})");
```
Comment (Sama34) [inline inc/datahandlers/user.php]: I assume `$this->delete_uids` is never going to be an empty value?

File: inc/functions.php [hunk 8]
```diff
@@ -2841,11 +2841,6 @@ function build_forum_jump($pid="0", $selitem="", $addselect="1", $depth="", $sho
 
 	$pid = (int)$pid;
 
-	if($permissions)
```
Comment (Sama34) [inline inc/functions.php]: The `$permissions` argument should be updated to `null` and the description updated to make it clear the passed value is never used anyways.

File: inc/class_datacache.php (hunk 6 above)
Comment (JN-Jones) [inline inc/class_datacache.php]: Can you guys stop this discussions please? It's unnecessary to cast this here as it's a save variable.

File: inc/datahandlers/user.php (hunk 7 above)
Comment (JN-Jones) [inline inc/datahandlers/user.php]: It shouldn't be, at least not in the core.

File: inc/functions.php (hunk 8 above)
Comment (Destroy666x) [inline inc/functions.php]: It is already empty. I'll update the description, why not.

File: inc/class_datacache.php (hunk 6 above)
Comment (Destroy666x) [inline inc/class_datacache.php]: > Does this means I'm entitled to revert your changes on my next PRs?

If that will be reasonable, feel free to. It's not like my changes should stay forever. But as @JN-Jones said, there is no point of casting an integer to integer. Actually, I see I used 2 redundant `(int)` castings too for some reason and will remove them in the next commit.

Also, I don't remember who, when and why made every PR... Do you?

File: admin/modules/tools/mailerrors.php (hunk 5 above)
Comment (Destroy666x) [inline admin/modules/tools/mailerrors.php]: Missed it, thanks, fixing.

**Comment by Stefan-ST** [comment]
@Destroy666x Hint for the future: Fixing too many issues with one PR makes testing harder than it could be. Also we could merge some fixes in case another doesn't work when they are separate PRs.

**Comment by Destroy666x** [comment]
@Stefan-ST , I know that. However, these aren't really big fixes and I had a mess with files so the easiest way to get around it was pushing them here.

**Comment by JN-Jones** [comment]
Though all of them are small changes it was difficult to test them. Three guys looked over it now and everyone found something new.

File: inc/class_datacache.php (hunk 6 above)
Comment (Sama34) [inline inc/class_datacache.php]: I'm not trying to discuss anything really. I'm concerned more about this fixing multiple bugs in the same PRs, having 11 files changed and most of the edits are because of why not. It makes it harder to test the code. Just saying.

I actually agree some changes are more readable now even when I wrote most of it. But, well I already said it.

**Comment by Cu8eR** [comment]
There should be one PR for one issue, but I have to agree with @Destroy666x - and why? Because there are many unmerged PRs (there were some weeks ago), it is not good. Every working and accepted PR should be merged immediately, in many cases  working PR has a conflict after some time, moreover it is really annoying to mainstain a lot of unmerged waiting PRs. It is just a waste of time.

**Comment by Destroy666x** [comment]
Yeah, agree with the above.

Also, it's good that 3 different people found bugs - the more testing the less to fix in the future. At the beginning when I joined the team I remember people merging their own PRs (or pushing directly) bigger than this - some effects of that are found until now.

**Comment by PaulBender** [comment]
Looks good now, merging.
