### PR TITLE
Fix #3669 User Last Visit / Active accuracy

### LINKED ISSUE #3669: Membership List(s): Last Visit / Active time may be incorrect
The Last Visit / Last Active time may be incorrect and shown as "1 minute ago" for users who have registered but then never logged in.

MyBB Version 1.8.20 
PHP Version 7.1.28
SQL Engine MySQLi 5.6.43

Suggested fixes:
In users.php
at line 3583
// $user['view']['lastactive'] = my_date('relative', $user['lastactive']); (LFG) 04-16-2019
 if($user['lastactive'])
{
$user['view']['lastactive'] = my_date('relative', $user['lastactive']);
}
else
{
$user['view']['lastactive'] = $lang-&gt;never;
}
In memberlist.php
at line 486
if($user['invisible'] == 1 &amp;&amp; $mybb-&gt;usergroup['canviewwolinvis'] != 1 &amp;&amp; $user['uid'] != $mybb-&gt;user['uid'])
 {
 $user['lastvisit'] = $lang-&gt;lastvisit_never;

 if($user['lastvisit'])
 {
 // We have had at least some active time, hide it instead
 $user['lastvisit'] = $lang-&gt;lastvisit_hidden;
 }
 }
 else
 {
 if($user['lastvisit'])
 {
 $user['lastvisit'] = my_date('relative', $user['lastactive']);
 }
 else
 {
 $user['lastvisit'] = $lang-&gt;lastvisit_never;
 }
 }

Original thread: [Membership List(s): Last Visit / Active time may be incorrect](https://community.mybb.com/thread-222691.html)

### PR DESCRIPTION
**Pull request by effone**
Attempt to fix #3669

### CODE REVIEW

**Comment by Ben-MyBB** [comment]
Solves #3669 correctly without any noticeable issues. Please can someone give it another glance over? @euantorano @kawaii @dvz

File: admin/modules/user/users.php [hunk 1]
```diff
@@ -1011,9 +1011,10 @@
 		}
 	}
 	$avatar_top = ceil((126-$scaled_dimensions['height'])/2);
-	if($user['lastactive'])
+	$last_seen = max(array($user['lastactive'], $user['lastvisit']));
```
Comment (euantorano) [inline admin/modules/user/users.php]: Super minor, but this can be written as `max($user['lastactive'], $user['lastvisit'])` - I'm not going to block the PR for this though, it's justa  note 😄
