### PR TITLE
Fixes #4504 - Twitch video code

### LINKED ISSUE #4504: Twitch video code is wrong
https://dev.twitch.tv/docs/embed/video-and-clips/

This needs a little change in
https://github.com/chack1172/mybb/blob/feature/jscripts/bbcodes_sceditor.js

Twitch video is not working anymore...

image

### PR DESCRIPTION
**Pull request by Eldenroot**
Thank you @yuliu 

Tested, works fine with one minor change.

Also fixed the indentation :)

Resolves #4504

### CODE REVIEW

File: inc/class_parser.php [hunk 1]
```diff
@@ -1479,8 +1479,8 @@ function mycode_parse_video($video, $url)
 		// Check URL is a valid URL first, as `parse_url` doesn't check validity.
 		if(false === filter_var($url, FILTER_VALIDATE_URL))
 		{
-            return "[video={$video}]{$url}[/video]";
```
Comment (cronlabspl) [inline inc/class_parser.php:1482]: what changed here?

**Review by cronlabspl — COMMENTED** [review]
seems like deleted and re-added lines without modification........

File: inc/class_parser.php (hunk 1 above)
Comment (Eldenroot) [reply inc/class_parser.php:1482]: Indentation :)

File: inc/class_parser.php [hunk 2]
```diff
@@ -1611,6 +1611,7 @@ function mycode_parse_video($video, $url)
 					// Channel (livestream) embed with URL like: https://twitch.tv/waypoint
 					$id = 'channel='.$path[1];
 				}
+				$parent_domain = parse_url($mybb->settings['bburl'], PHP_URL_HOST);
```
Comment (yuliu) [inline inc/class_parser.php]: It might be good to:
 - rename the variable to `$bbdomain`, and
 - initialize it as a _static_ variable somewhere in the beginning of the function.

File: inc/class_parser.php [hunk 3]
```diff
@@ -1469,18 +1469,20 @@ function mycode_parse_email_callback($matches)
...
 	{
-		global $templates;
+		global $mybb, $templates;
 
 		if(empty($video) || empty($url))
 		{
 			return "[video={$video}]{$url}[/video]";
 		}
 
+		$bbdomain = parse_url($mybb->settings['bburl'], PHP_URL_HOST);
```
Comment (yuliu) [inline inc/class_parser.php]: It'd be good to make the variable `static`, I think.

Comment (yuliu) [reply inc/class_parser.php]: Sorry, my bad.

File: inc/class_parser.php [hunk 4]
```diff
@@ -1479,15 +1479,16 @@ function mycode_parse_video($video, $url)
...
+			return "[video={$video}]{$url}[/video]";
+		}
 
 		$parsed_url = @parse_url(urldecode($url));
 		if($parsed_url === false)
 		{
 			return "[video={$video}]{$url}[/video]";
 		}
 
+		$bbdomain = parse_url($mybb->settings['bburl'], PHP_URL_HOST);
```
Comment (yuliu) [inline inc/class_parser.php]:
```suggestion
		$bbdomain = parse_url($mybb->settings['bburl'], PHP_URL_HOST);

```

**Review by yuliu — APPROVED** [review]
I was thinking about using a static variable but just realized that doing the following isn't quite worth the effort:
```php
static $bbdomain = '';
if(empty($bbdomain))
{
$bbdomain = parse_url($mybb->settings['bburl'], PHP_URL_HOST);
}
```
By the way, I'm so sorry about messing up this PR.

**Comment by Eldenroot** [comment]
Nevermind @yuliu - happy to fix it :)

**Comment by Xazin** [comment]
Looks clean, if it works this is a good solution.

**Comment by Eldenroot** [comment]
@Xazin - yes, works fine!

**Comment by dvz** [comment]
You can bump the template version to `1831`

**Comment by Eldenroot** [comment]
> You can bump the template version to `1831`

Done!
