### PR TITLE
Fixes #3245, #3344 Video MyCode Bug

### LINKED ISSUE #3245: Mixer video mycode
We should add support to the `[video]` MyCode for [Mixer](https://mixer.com).

The embed codes take the following form:

```HTML
<iframe allowfullscreen="true" src="https://mixer.com/embed/player/SmiteGame?disableLowLatency=1" width="620" height="349"> </iframe>
```

Note that `SmiteGame` is the name of the streamer/channel.

I cannot find a way to embed archives of past streams, I'm not entirely sure if that's possible on mixer as it is on Twitch...

### PR DESCRIPTION
**Pull request by effone**
Attempt to fix #3245, #3344 
1. Implement Mixer Video Embed
2. Video MyCode Bug

### CODE REVIEW

File: jscripts/bbcodes_sceditor.js [hunk 1]
```diff
@@ -480,12 +480,12 @@ $(document).ready(function($) {
 						url     = matches ? 'https://www.facebook.com/video/embed?video_id=' + matches[1] : false;
 						break;
 					case 'liveleak':
-						matches = content.match(/liveleak\.com\/(?:view\?i=)([^\/]+)/);
+						matches = content.match(/liveleak\.com\/(?:view\?[a-z]{1}=)([^\/]+)/);
```
Comment (euantorano) [inline jscripts/bbcodes_sceditor.js]: This `{1}` shouldn't be necessary here surely? Shouldn't `[a-z]` alone achieve the same thing, or am I missing something?

Comment (effone) [reply jscripts/bbcodes_sceditor.js]: Of course! My bad.

**Comment by effone** [comment]
PR complete.
