### PR TITLE
Fixes #2659 Double recipients with private messages

### LINKED ISSUE #2659: Double recipients with private messages
How to reproduce with MyBB 1.8.10 default theme and language.

Write a private message to three or more members, one member receives and read the message and do Reply All, now if the member click on "preview" recipients have doubled!

### PR DESCRIPTION
**Pull request by effone**
Attempt to fix #2659 
Duplicate PM Receipient Fix

### CODE REVIEW

**Comment by effone** [comment]
I don't know if I did correctly but I have investigated every possible backend output and it appeared like backend is working perfectly. This repeated name is generated by js only while malprocessing a space character. May be I am wrong.

**Comment by Shade-** [comment]
You're right – even myself proposed this fix back in the days. However, I feel like an array_unique on the backend side is still necessary just to filter out any mistakes on the front end side.

**Comment by effone** [comment]
Is it okay now?

File: xmlhttp.php [hunk 1]
```diff
@@ -281,6 +281,9 @@
 		}
 	}
 
+	// Filter out duplicates, if any, from recursive array data
+	$data = array_intersect_key($data, array_unique(array_map('serialize', $data)));
```
Comment (euantorano) [inline xmlhttp.php]: This should use `my_serialize` rather than plain old `serialize`: https://github.com/mybb/mybb/blob/feature/inc/functions.php#L2289

That way things like multibyte strings and such are taken care of, which could be possible for user names.

Comment (effone) [reply xmlhttp.php]: Done.

File: private.php [hunk 2]
```diff
@@ -704,8 +705,8 @@
 		{
 			$optionschecked['readreceipt'] = 'checked="checked"';
 		}
-		$to = htmlspecialchars_uni($mybb->get_input('to'));
-		$bcc = htmlspecialchars_uni($mybb->get_input('bcc'));
+		$to = htmlspecialchars_uni(implode(', ',array_unique(array_map('trim', explode(',', $mybb->get_input('to'))))));
```
Comment (Shade-) [inline private.php]: I know I might seem pedant here, but there should be a space between `implode(', ',` and `array_unique` :)

Comment (effone) [reply private.php]: Done.

File: xmlhttp.php [hunk 3]
```diff
@@ -281,6 +281,9 @@
 		}
 	}
 
+	// Filter out duplicates, if any, from recursive array data
+	$data = array_intersect_key($data, array_unique(array_map('my_serialize', $data)));
```
[the remark this answers is not in the document]
Comment (effone) [reply xmlhttp.php]: For any impossible duplicate returned from database 👯‍♂️ 
I'll remove it ...

[the remark this answers is not in the document]
Comment (Shade-) [reply xmlhttp.php]: 😁

[the remark this answers is not in the document]
Comment (effone) [reply xmlhttp.php]: Removed.
