### PR TITLE
Fixes #4025 Insert image width & height uses incorrect MyCode

### LINKED ISSUE #4025: Inserting image in editor with width & height uses incorrect MyCode
From Discord #18-support:

Quote:@Omnipotent 09/01/2019
Nice, MyBB image buttons are messed up for me because it translates into [img height=* width=*] instead of [img=*x*] so it doesn't get parsed

Note if you switch out of source mode it will fix the syntax but if you post it without switching the mode then it will give an invalid img tag which won't be parsed.

Anyway I am sure someone will open a report on the github and it will get fixed.

Test code:

[img width=1 height=2]aaaa[/img]

Original thread: [Editor's source mode of inserting an image with width/height](https://community.mybb.com/thread-224668.html)

### PR DESCRIPTION
**Pull request by demtor**
Resolves #4025 

The format part  can be omitted for an actual bug of SCEditor: it should format to the new syntax `[img width="" height=""]`  but it is stuck to an old syntax (I guess) which matches to the mybb current one:

https://github.com/samclarke/SCEditor/blob/7fd14aecc6f0c68f1e8bb98b12f6f0da769c671a/src/formats/bbcode.js#L578-L579

So I added it in case they are gonna resolve it one day.

### CODE REVIEW

File: jscripts/bbcodes_sceditor.js [hunk 1]
```diff
@@ -522,6 +522,76 @@ $(function ($) {
...
+				'</div>' +
+				'<div>' +
+				'<label for="width">' + editor._('Width (optional)') + ':</label> ' +
+				'<input type="text" id="width" size="2" />' +
+				'</div>' +
+				'<div>' +
+				'<label for="height">' + editor._('Height (optional)') + ':</label> ' +
+				'<input type="text" id="height" size="2" />' +
+				'</div>' +
+				'<div><input type="button" class="button" value="' + editor._('Insert') + '" /></div>' +
```
Comment (JordanMussi) [inline jscripts/bbcodes_sceditor.js:563]:
```suggestion
				'<div>' +
				'<input type="button" class="button" value="' + editor._('Insert') + '" />' +
				'</div>' +
```

**Review by JordanMussi — CHANGES_REQUESTED** [review]
Great stuff this is all working for me :-)

One minor thing for consistency 👇

**Comment by JordanMussi** [comment]
*Note to self: cache busting will need bumping when merging*

**Review by JordanMussi — APPROVED** [review]
This could probably sneak into 1.8.23 along with #4082...

**Comment by JordanMussi** [comment]
Thank you @demtor!
